apiVersion: apps/v1
kind: Deployment
metadata:
  name: taco-deployment
  labels:
    app: taco
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taco
  template:
    metadata:
      labels:
        app: taco
    spec:
      containers:
        - name: taco
          image: asia-south1-docker.pkg.dev/analog-grin-461709-r9/homelab-repo/taco:v2
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 30
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            failureThreshold: 1
            successThreshold: 1
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            failureThreshold: 10
            successThreshold: 1
          ports:
            - containerPort: 8080
